In [78]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1. NumPy Array

In [79]:
import numpy as np

In [80]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
a[0]

1

In [82]:
a[2:5]

array([3, 4, 5])

In [83]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [84]:
a[:3]

array([1, 2, 3])

In [85]:
a[-1]

10

In [86]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [87]:
a[-5:-1]

array([6, 7, 8, 9])

In [88]:
np.size(a)

10

In [89]:
np.shape(a)

(10,)

In [90]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
a[0,0]

1

In [92]:
a[1,:]

array([4, 5, 6])

In [93]:
a[:,-1]

array([3, 6, 9])

In [94]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [95]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

4

In [96]:
np.size(a,1)

3

In [97]:
np.ndim(a)

2

In [98]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [99]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

# 2. Special Type of Matrix

In [100]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [101]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [102]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [103]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [104]:
c*d

array([[8., 0.],
       [0., 8.]])

In [105]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [106]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [107]:
np.empty([5,5])

array([[6.92461179e-310, 6.92461179e-310, 4.58492919e-321,
        5.43472210e-323, 6.92457427e-310],
       [4.65139071e-310, 4.94065646e-324, 0.00000000e+000,
        0.00000000e+000, 6.92457426e-310],
       [4.94065646e-324, 0.00000000e+000, 6.92457426e-310,
        4.79243676e-322, 6.92461179e-310],
       [6.92461179e-310, 4.65138924e-310, 4.65138923e-310,
        4.65138924e-310, 4.65138923e-310],
       [6.92460959e-310, 6.92461191e-310, 6.92461191e-310,
        6.92461191e-310, 1.02765654e-321]])

# 3.Random

In [108]:
import numpy as np
np.random.rand()

0.18093370605501313

In [109]:
np.random.randint(5)

1

In [110]:
np.random.seed(5)
np.random.randint(2,5)

4

In [111]:
np.random.rand(5,5)

array([[0.87073231, 0.20671916, 0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 , 0.18772123, 0.08074127],
       [0.7384403 , 0.44130922, 0.15830987, 0.87993703, 0.27408646],
       [0.41423502, 0.29607993, 0.62878791, 0.57983781, 0.5999292 ],
       [0.26581912, 0.28468588, 0.25358821, 0.32756395, 0.1441643 ]])

In [112]:
np.round(np.random.rand(5,5))

array([[0., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 0., 0.],
       [1., 0., 1., 1., 1.]])

In [113]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([7, 9, 1, 6, 3])

##### สามารถเลือกซ้ำได้

In [114]:
np.random.choice(a,5, replace = False)

array([ 2,  3,  6,  5, 10])

##### ไม่สามารถเลือกซ้ำได้

In [115]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.84505523, 0.64368206, 0.13424074, 0.17672245, 0.31886793],
       [0.8113844 , 0.99443124, 0.35272314, 0.4840603 , 0.7421301 ],
       [0.42420571, 0.56635137, 0.21497922, 0.15703111, 0.83581416]])

In [116]:
#Ex.2 Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
np_matrix = np.random.rand(10,5)
a = np.round(np_matrix[:,-1])
np_matrix[:,-1] = a
np_matrix

array([[0.85970689, 0.11111075, 0.47833904, 0.84998003, 1.        ],
       [0.44660783, 0.80047642, 0.02039138, 0.57261865, 0.        ],
       [0.9851368 , 0.80140153, 0.0539621 , 0.19047777, 0.        ],
       [0.70294208, 0.33204815, 0.3599832 , 0.92147057, 1.        ],
       [0.40768573, 0.89857115, 0.33025325, 0.08273857, 1.        ],
       [0.66084439, 0.89298429, 0.96515755, 0.76993268, 1.        ],
       [0.71004905, 0.70155283, 0.76733138, 0.97434948, 0.        ],
       [0.08305444, 0.23964044, 0.22148276, 0.3635998 , 1.        ],
       [0.06009617, 0.44974356, 0.81317053, 0.26423837, 0.        ],
       [0.24210767, 0.08507046, 0.80777744, 0.17025008, 0.        ]])

In [117]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 5,  1,  1,  0,  8],
       [ 0,  5, 10,  9,  3],
       [ 3,  0,  3,  7,  3],
       [ 7,  3,  2,  6,  6],
       [ 2,  7,  0,  3,  7]])

In [118]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 1, 2, 1, 2],
       [2, 1, 1, 1, 2],
       [2, 2, 2, 0, 2],
       [1, 2, 0, 0, 0],
       [1, 0, 1, 1, 0]])

In [119]:
i,j = np.where(np_matrix == 2)

In [120]:
i

array([0, 0, 1, 1, 2, 2, 2, 2, 3])

In [121]:
j

array([2, 4, 0, 4, 0, 1, 2, 4, 1])

In [122]:
#Ex 3. Why we cannot use this index ? Please fix it !!
np_matrix = np.random.randint(3,size = (6,5))
idx = [1,2,3,4,5]
np_matrix[idx,:]

array([[0, 0, 2, 2, 1],
       [1, 2, 2, 1, 2],
       [0, 2, 0, 0, 1],
       [1, 1, 2, 1, 0],
       [1, 1, 0, 0, 2]])

In [123]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[2, 2, 1, 0, 1],
       [0, 2, 0, 0, 1],
       [1, 1, 2, 1, 0],
       [1, 1, 0, 0, 2]])

In [124]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[2, 2, 8, 9, 1],
       [8, 6, 7, 9, 6],
       [1, 8, 2, 4, 9],
       [5, 9, 1, 8, 6],
       [1, 5, 1, 8, 8]])

In [125]:
result = (np_matrix == 2)
result

array([[ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [126]:
np_matrix[result] = 99
np_matrix

array([[99, 99,  8,  9,  1],
       [ 8,  6,  7,  9,  6],
       [ 1,  8, 99,  4,  9],
       [ 5,  9,  1,  8,  6],
       [ 1,  5,  1,  8,  8]])

#### Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
#### Then, randomly create a label vector for 10 samples. 
#### Finally, seperate samples into 2 groups
#### Group 1 called train_data (label == 0)
#### Group 2 called test_data (label == 1)

### data_matrix

In [127]:
data_matrix = np.random.randint(10,size=(10,5))
data_matrix

array([[8, 3, 3, 9, 7],
       [0, 8, 7, 3, 4],
       [7, 0, 6, 3, 1],
       [5, 1, 0, 3, 4],
       [0, 8, 3, 8, 5],
       [2, 7, 6, 5, 2],
       [6, 7, 6, 5, 1],
       [6, 0, 2, 5, 7],
       [5, 5, 2, 4, 4],
       [3, 9, 0, 8, 1]])

### label

In [128]:
label_vector = np.random.randint(2,size=(10))
label_vector

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 1])

### train_data

In [129]:
train_data = (label_vector == 0)
data_matrix[train_data]

array([[8, 3, 3, 9, 7],
       [7, 0, 6, 3, 1],
       [5, 1, 0, 3, 4],
       [0, 8, 3, 8, 5]])

### test_data

In [130]:
test_data = (label_vector == 1)
data_matrix[test_data]

array([[0, 8, 7, 3, 4],
       [2, 7, 6, 5, 2],
       [6, 7, 6, 5, 1],
       [6, 0, 2, 5, 7],
       [5, 5, 2, 4, 4],
       [3, 9, 0, 8, 1]])

In [131]:
data = np.random.randint(5,size=(5,5)) +1
data

array([[5, 2, 2, 3, 1],
       [4, 3, 5, 4, 4],
       [4, 4, 2, 2, 1],
       [2, 3, 5, 3, 3],
       [3, 5, 5, 4, 2]])

# 4.Important Function

In [132]:
np.max(data)

5

In [133]:
np.max(data,0)

array([5, 5, 5, 4, 4])

In [134]:
np.max(data,1)

array([5, 5, 4, 5, 5])

In [135]:
np.sum(data)

81

In [136]:
np.average(data)

3.24

In [137]:
data[0,:]

array([5, 2, 2, 3, 1])

In [138]:
np.argmax(data[0,:])

0

In [139]:
np.argmin(data[0,:])

4

In [140]:
np.sort(data[0,:])

array([1, 2, 2, 3, 5])

In [141]:
np.argsort(data[0,:])

array([4, 1, 2, 3, 0])

In [142]:
#Ex.5 How to sort in decreasing order using np.sort
np.sort(data[0,:])[::-1]

array([5, 3, 2, 2, 1])

In [143]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [144]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [145]:
data = np.round(np.random.random((5,5))*3)
data

array([[1., 2., 2., 1., 0.],
       [1., 0., 2., 2., 0.],
       [1., 3., 1., 2., 1.],
       [1., 0., 2., 2., 2.],
       [1., 2., 2., 2., 1.]])

In [146]:
data.shape

(5, 5)

In [147]:
data.reshape(1,25)

array([[1., 2., 2., 1., 0., 1., 0., 2., 2., 0., 1., 3., 1., 2., 1., 1.,
        0., 2., 2., 2., 1., 2., 2., 2., 1.]])

In [148]:
tile = [[1,2],
        [3,4]]
tile

[[1, 2], [3, 4]]

In [149]:
np.tile(tile,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [150]:
#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [151]:
result = (np_test%3 == 0)
np_test[result]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [152]:
#Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
np_test[np.fill_diagonal(np_test,0)]
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0]])