In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1. NumPy Array

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

In [ ]:
a[0]

In [ ]:
a[2:5]

In [ ]:
a[:6]

In [ ]:
a[:3]

In [ ]:
a[-1]

In [ ]:
a[-5:]

In [ ]:
a[-5:-1]

In [ ]:
np.size(a)

In [ ]:
np.shape(a)

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
a[0,0]

In [ ]:
a[1,:]

In [ ]:
a[:,-1]

In [ ]:
a[:,-1] = 0
a

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

In [ ]:
np.size(a,1)

In [ ]:
np.ndim(a)

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

In [ ]:
np.array(np_mix_matrix[:,1], dtype = int)

# 2. Special Type of Matrix

In [ ]:
a = np.zeros((2,2))
a

In [ ]:
b = np.ones((2,2))
b

In [ ]:
c = np.full((2,2),8)
c

In [ ]:
d = np.eye(2)
d

In [ ]:
c*d

In [ ]:
2*np.ones((2,2))

In [ ]:
np.sqrt(np.full((2,2),4))

In [ ]:
np.empty([5,5])

# 3.Random

In [26]:
import numpy as np
np.random.rand()

0.853707352147294

In [ ]:
np.random.randint(5)

In [ ]:
np.random.seed(5)
np.random.randint(2,5)

In [ ]:
np.random.rand(5,5)

In [ ]:
np.round(np.random.rand(5,5))

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

##### สามารถเลือกซ้ำได้

In [ ]:
np.random.choice(a,5, replace = False)

##### ไม่สามารถเลือกซ้ำได้

In [ ]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

In [27]:
#Ex.2 Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
np_matrix = np.random.rand(10,5)
a = np.round(np_matrix[:,-1])
np_matrix[:,-1] = a
np_matrix

array([[0.62398987, 0.94529139, 0.55000117, 0.20585259, 0.        ],
       [0.91360324, 0.52712579, 0.23138919, 0.65746425, 1.        ],
       [0.32206943, 0.48803289, 0.54241186, 0.23477234, 0.        ],
       [0.50368204, 0.75860643, 0.76605938, 0.63306475, 1.        ],
       [0.7729504 , 0.34319263, 0.72859327, 0.42703863, 0.        ],
       [0.03008861, 0.5563726 , 0.03140352, 0.66281947, 1.        ],
       [0.71966343, 0.46018501, 0.72821445, 0.68080622, 0.        ],
       [0.66293842, 0.4489101 , 0.67570714, 0.44230057, 0.        ],
       [0.68183396, 0.64607922, 0.04601679, 0.836861  , 0.        ],
       [0.18388198, 0.17550033, 0.85030196, 0.88566931, 0.        ]])

In [34]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 9,  4,  0,  6,  3],
       [ 5,  9,  4,  4,  2],
       [ 0,  7,  9,  3,  5],
       [ 8,  9,  4,  9,  0],
       [ 1,  5, 10, 10,  6]])

In [35]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 0, 1, 1, 0],
       [1, 2, 0, 0, 2],
       [1, 0, 0, 1, 1],
       [1, 0, 2, 0, 1],
       [2, 0, 1, 2, 2]])

In [36]:
i,j = np.where(np_matrix == 2)

In [37]:
i

array([0, 1, 1, 3, 4, 4, 4])

In [38]:
j

array([0, 1, 4, 2, 0, 3, 4])

In [39]:
#Ex 3. Why we cannot use this index ? Please fix it !!
np_matrix = np.random.randint(3,size = (6,5))
idx = [1,2,3,4,5]
np_matrix[idx,:]

array([[2, 0, 1, 1, 0],
       [1, 2, 0, 0, 2],
       [1, 0, 0, 1, 1],
       [1, 0, 2, 0, 1],
       [2, 0, 1, 2, 2]])

In [ ]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

In [ ]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

In [ ]:
result = (np_matrix == 2)
result

In [ ]:
np_matrix[result] = 99
np_matrix

#### Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
#### Then, randomly create a label vector for 10 samples. 
#### Finally, seperate samples into 2 groups
#### Group 1 called train_data (label == 0)
#### Group 2 called test_data (label == 1)

### data_matrix

In [ ]:
data_matrix = np.random.randint(10,size=(10,5))
data_matrix

### label

In [ ]:
label_vector = np.random.randint(2,size=(10))
label_vector

### train_data

In [ ]:
train_data = (label_vector == 0)
data_matrix[train_data]

### test_data

In [ ]:
test_data = (label_vector == 1)
data_matrix[test_data]

In [ ]:
data = np.random.randint(5,size=(5,5)) +1
data

# 4.Important Function

In [ ]:
np.max(data)

In [ ]:
np.max(data,0)

In [ ]:
np.max(data,1)

In [ ]:
np.sum(data)

In [ ]:
np.average(data)

In [ ]:
data[0,:]

In [ ]:
np.argmax(data[0,:])

In [ ]:
np.argmin(data[0,:])

In [ ]:
np.sort(data[0,:])

In [ ]:
np.argsort(data[0,:])

In [ ]:
#Ex.5 How to sort in decreasing order using np.sort
np.sort(data[0,:])[::-1]

In [ ]:
np.arange(1,10,2)

In [ ]:
np.linspace(5,10,10)

In [ ]:
data = np.round(np.random.random((5,5))*3)
data

In [ ]:
data.shape

In [ ]:
data.reshape(1,25)

In [ ]:
tile = [[1,2],
        [3,4]]
tile

In [ ]:
np.tile(tile,(4,1))

In [ ]:
#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

In [ ]:
result = (np_test%3 == 0)
np_test[result]

In [ ]:
#Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
np_test[np.fill_diagonal(np_test,0)]
np_test